[Variables]
; --- skin config
HideOnDesktop = 0
ShowLabels = 1
ShowGraph = 1
ShowValuesInBars = 1
ShowFramerate = 1

BarDivisor = 5

; style
Padding = 10

FontColor = 0,215,255
BackgroundColor = 0,0,0,200
FramerateCounterSize = 50

CpuColor = 0,175,225
GpuColor = 0,225,175
RamColor = 225,0,175

LabelHeight = 20

DivisorWidth = 0.4
DivisorColor = 255,255,255

BarHeight = 100
BarWidth = 20
BarBackgroundColor = 150,150,150,255
BarMarkerColor = #BackgroundColor#
BarMarkerThickness = 0.75
BarColorSafe = 125,200,150
BarColorWarning = 220,210,0
BarColorAlert = 225,100,100

GraphHeight = 100
