[Variables]
; --- skin config
HideOnDesktop = 0
ShowLabels = 1
ShowGraph = 1
ShowValuesInBars = 1
ShowFramerate = 1

BarDivisor = 5

; --- style
Padding = 10

FontColor = 255,255,255
BackgroundColor = 0,0,0,50
BackgroundBorderWidth = 0
FramerateCounterSize = 50

CpuColor = 200,200,255
GpuColor = 200,255,200
RamColor = 255,175,230

LabelHeight = 20

DivisorWidth = 0.4
DivisorColor = 255,255,255

BarHeight = 100
BarWidth = 20
BarBackgroundColor = 255,255,255,50
BarMarkerColor = 50,50,50
BarMarkerThickness = 0.75
BarColorSafe = 100,200,100
BarColorWarning = 220,210,0
BarColorAlert = 225,100,100

GraphHeight = 100
