[Rainmeter]
DefaultAlwaysOnTop = 2
Update = 500

[Variables]
; --- hardware config
TargetFramerate = 144
CpuUsageAlert = 90
CpuUsageWarning = 75
CpuTempAlert = 90
CpuTempWarning = 80
GpuUsageAlert = 101
GpuUsageWarning = 100
GpuTempAlert = 90
GpuTempWarning = 75
VRamAlert = 90
VRamWarning = 80
VRamTotal = 8079
RamAlert = 90
RamWarning = 80

; --- skin config
BarDivisor = 5
ShowValuesInBars = 1
HideOnDesktop = 0